title: Athian Documentation Library
email: dory@athian.ag
description: Public library for Athian governance and protocol documentation.
baseurl: "/documents"
url: "https://athian-ai.github.io"
markdown: kramdown
theme: minimal
